### ISSUE TITLE
Exception from HRESULT: 0x82DA0101

### ISSUE THREAD

**Issue by Loadingxex** [XboxChaos/Assembly#172]
System.Runtime.InteropServices.COMException (0x82DA0101): Exception from HRESULT: 0x82DA0101   at XDevkit.IXboxConsole.ScreenShot(String Filename)   at XBDMCommunicator.Xbdm.GetScreenshot(String savePath, Boolean freezeDuring)   at Assembly.Windows.Home.menuScreenshot_Click(Object sender, RoutedEventArgs e)   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ChadSki** [comment]
I don't have personal experience with this error, but Google search tells me "It appears this is a general error when your xbox doesn't respond fast enough. If you're using wireless try restarting your wireless router and then it should work."

**Comment by Loadingxex** [comment]
It ended up just being the plugins , to many of them ig but thanks so much I'm surprised how reliable help is
