### ISSUE TITLE
Unable to start; hangs PC/Window

### ISSUE THREAD

**Issue by rocket4wheel** [XboxChaos/Assembly#173]
I have tried running this program for two days, trying a whole bunch of different versions, different operating systems, **different PC's altogether**, but none of them work.

Whenever I download it, through the chaos downloader or straight from github, attempting to use both master and _dev_, _all it does after running is freeze the window, or the whole PC **(Which is really bad)**_. Whenever I try to end it, the process runs in System, so i have to restart the computer before I can delete it. Even then, whenever I run it sometimes, it is still running in system for some reason. I am running on windows 10 with the latest updates, i have tried it on 8 and 7, but it will not work.

I have tried downloading and running the sourceforge version back in 2013. It runs, but it hangs and doesn't start again after updating. I really want to use this program for reach!

**Comment by ThunderWaffle** [comment]
Assembly should run on all of those OS'es.  Are you getting any exceptions?

I really can't explain why Assembly is running as System for you.  It's probably likely that between your two PC's you have something installed that's magically conflicting with Assembly.  I have no clue what that would be though.

**Comment by rocket4wheel** [comment]
I just killed a whole bunch of useless processes and all non-windows processes. Didnt help. However, when I run it with the downloader, it starts rundll32 and hangs that.

**Comment by rocket4wheel** [comment]
I just ran it on a third PC with windows 8.1 and it worked.
