### ISSUE TITLE
Access to the path 

### ISSUE THREAD

**Issue by Fireflame5500** [XboxChaos/Assembly#183]
The program asked for an update. I said yes obviously and now the permissions have changed and I cannot remove the program even though I am the administrator of this computer.

**Comment by ChadSki** [comment]
>cannot remove the program even though I am the administrator of this computer.

That's strange. What filepath is it located at?

**Comment by Fireflame5500** [comment]
Software, Xeraxic, Assembly. I ended up fixing this by going into regedit and removing the entire Xeraxic folder, then I went into safe mode and I was able to remove everything without issue. After I installed Assembly again I didn't take the update and everything worked fine.
