### ISSUE TITLE
Attempted to perform an unauthorized operation.

### ISSUE THREAD

**Issue by gatnexsedever** [XboxChaos/Assembly#184]
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value)   at Assembly.Helpers.AssemblyProtocol.UpdateProtocol()   at Assembly.App.OnStartup(StartupEventArgs e)   at System.Windows.Application.

**Comment by gatnexsedever** [comment]
what should i do ?

**Comment by 0xdeafcafe** [comment]
Make sure you're running the app as admin - it's unable to modify your registry keys.

**Comment by ChadSki** [comment]
If admin rights are required, shouldn't Assembly do a UAC prompt at startup?
