### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by C0derDave** [XboxChaos/Assembly#187]
System.NullReferenceException: Object reference not set to an instance of an object.   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.

Trying to open a map file for Halo Online.

**Comment by ThunderWaffle** [comment]
Halo Online is not supported by the main version of Assembly.

@Lord-Zedd Is there still a fork that supports HO?

**Comment by Lord-Zedd** [comment]
Yes https://github.com/Lord-Zedd/Assembly
A pre-compiled version should be on the halo online reddit somewhere

**Comment by C0derDave** [comment]
I found it, thanks.

**Comment by 0xdeafcafe** [comment]
What state is it in @Lord-Zedd?

**Comment by Lord-Zedd** [comment]
I didnt make it originally, i forked it for plugins mainly. But basic functionality is there, scripts (i did those) but no locales, no injection or block add/subtract.
