### ISSUE TITLE
Invalid cache file header magic

### ISSUE THREAD

**Issue by TLT123** [XboxChaos/Assembly#188]
System.ArgumentException: Invalid cache file header magic   at Blamite.Blam.CacheFileLoader.DetermineCacheFileEndianness(Byte[] headerMagic)   at Blamite.Blam.CacheFileLoader.LoadCacheFile(IReader reader, BuildInfoLoader infoLoader, BuildInformation

**Comment by ThunderWaffle** [comment]
Its impossible to debug exceptions without some context as to what you doing.
What map?
What game?

**Comment by ThunderWaffle** [comment]
Closing since OP did not reply.
