### ISSUE TITLE
Im using assembly with Eldewrito and trying to create patches

### ISSUE THREAD

**Issue by Stinger05189** [XboxChaos/Assembly#191]
![screenshot 392](https://user-images.githubusercontent.com/33469333/33511195-2eb03b08-d6dc-11e7-861e-19bfb8db4fb2.png)
I tried messing with input/output .map file but im not sure what im doing wrong...?

**Comment by ThunderWaffle** [comment]
Compile this fork instead.

https://github.com/HaydnTrigg/Assembly/commits/master

**Comment by ThunderWaffle** [comment]
@Lord-Zedd Next time you push can you update the readme about Halo: Online?

**Comment by Stinger05189** [comment]
So your saying to use that version of assembly with halo online?
I downloaded it and wasnt sure what to do with it. Just trying to make patches that allow me to create several large tagmods and apply them ingame.

**Comment by Lord-Zedd** [comment]
99.9% sure that even with the correct fork, the patcher does not support Halo Online. You'll have to ask around the halo online reddit or discord on how to set up patches using TagTool. Going to close this.
