### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection.Parameter name: index

### ISSUE THREAD

**Issue by jackrabbit72380** [XboxChaos/Assembly#199]
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.Parameter name: index   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.

error occurred when trying to duplicate scenario tag

**Comment by Lord-Zedd** [comment]
What map?

**Comment by 0xdeafcafe** [comment]
Closing due to age.
