### ISSUE TITLE
Read/Write access issues post map load. 

### ISSUE THREAD

**Issue by Akarias** [XboxChaos/Assembly#205]
After a user has loaded a map, they may proceed to use another program to also alter the map file such as a hex editor. While the file is locked and in use by another process the user will encounter exceptions based on what they may be doing:

- Selecting a tag for the MetaEditor to load
- Saving changes to an already open tag in the MetaEditor
- Reloading the MetaEditor 

I'm not too familiar with how Assembly likes to deal with exceptions, but Blamite FileStreamManager does not seem to expose any exceptions caused by OpenRead(), OpenWrite() & OpenReadWrite(). Of course we could just slap a try around button actions to catch the exception for now. Same for loading tags into the MetaEditor but that is less than elegant.

Of course anyone sitting in visual studio will know exactly what to do. 

Thoughts? 

#206

**Comment by Lord-Zedd** [comment]
Assembly expects a debugger to be present when compiled as debug, causing the crashes. Exceptions will throw normally when compiled as release.

**Comment by Akarias** [comment]
Well that explains a few things and that the vast majority of people ive spoken to are on predownloaded debug releases...
