### ISSUE TITLE
"Forceload..." Plugin detection issue.

### ISSUE THREAD

**Issue by Akarias** [XboxChaos/Assembly#217]
```
System.IO.FileNotFoundException: Could not find file
'Assembly\bin\x64\Release\Plugins\ReachMCC\vehi.xml'.
```
**Temp fix:** manually copy missing plugins from the Reach plugin folder to ReachMCC.

I haven't looked at how plugin loading is dealt with for ReachMCC but its simple enough to sort out.

**Comment by Lord-Zedd** [comment]
should be fixed now
