### ISSUE TITLE
Struct Copying

### ISSUE THREAD

**Issue by DeadCanadian** [XboxChaos/Assembly#22]
Under the information drop-down (which still needs to be styled) for structs it would be nice to have a button to copy a single struct and be able to paste it in another struct (of equal size) so we wouldn't need to re-type all the information into the new one.

**Comment by ChadSki** [comment]
Was this implemented, or closed as won't fix?

**Comment by Lord-Zedd** [comment]
Implemented in dev branch starting with 07d19b09d2b18f4e329eb8e6b82ded20c2099f97
