### ISSUE TITLE
Assembly\Windows\Home.xaml size can exceed screen resolutions

### ISSUE THREAD

**Issue by Akarias** [XboxChaos/Assembly#222]
![bUx8FjJKsH](https://user-images.githubusercontent.com/5367361/70392358-44bb2580-19d7-11ea-8c06-fb10e47e0a14.png)

Users with monitors that have varied resolutions can encounter the main window exceeding, for example I use 2560x1440 for my main monitor and a 2560x1080 as a secondary. I encounter this quite a bit.

Having the window maximized does not cause this issue, as the last used screen is remembered, but snapping to either side of the screen or screen corners will. 

To replicate: Open assembly on a monitor with a larger resolution than other connected monitors & resize the window to take up as much vertical space as possible, windows aero snapping will suffice (Windows Key+Arrow Keys). Close assembly. Reopen assembly while focus is on another monitor that has a smaller resolution, see results.

Work around: Use the aero snapping hotkeys to resize the window (Windows Key+Arrow Keys), depending on the resolution the user may not be able to actually reach any elements that let them resize the window.

**Comment by 0xdeafcafe** [comment]
Not sure I want to sink time into this. It's trivial, especially with multi monitors. If enough people complain I can revisit.
