### ISSUE TITLE
Cant import xbox360 tags to mcc pc (endianness issue)

### ISSUE THREAD

**Issue by I-found-me-a-bug** [XboxChaos/Assembly#223]
So you cant import tagc files that where exported from an xbox 360 .map file to mcc pc. blamite.dll will throw an exception when importing the tagc file. i for example used this one https://www.xboxchaos.com/files/file/154-halo-reach-giant-tag/. when i import it into assembly i get an exception from blamite.dll that the tagc file is not valid.

the exact error:
`Exception thrown: 'System.ArgumentException' in Blamite.dll
An unhandled exception of type 'System.ArgumentException' occurred in Blamite.dll
Not a valid tag container file`

this is because the first 4 chars in the tagc container are "cgat" instead of "ctag"

I have tested injecting the tag into halo reach using a .map file from the xbox 360 version and it works fine.

the error i think has to do with the encoding and decoding with different endianness as the xbox 360 was big endian and x86 is little endian. When I checked both the downloaded file and another tagc file I exported from the mcc pc reach version with a hex editor this appeared to be the case.

I think the fix should be as simple as checking endianness when tagc is imported and converting it if it does not match the current .map files' endianness

**Comment by Lord-Zedd** [comment]
This is on purpose. The data itself is also in the wrong endian so it isnt an easy fix.
