### ISSUE TITLE
Network synchronized poking

### ISSUE THREAD

**Issue by ThunderWaffle** [XboxChaos/Assembly#227]
We worked on network synced poking 5 years ago but never finished it.  It would be nice if we came back around to that on PC.

**Comment by ThunderWaffle** [comment]
Basics of this feature are implemented on netpoke2.

Still want to add memory command batching and one security feature to make the sessions host only pokes.

**Comment by 0xdeafcafe** [comment]
Can you open a draft PR so it can be linked to this issue?
