### ISSUE TITLE
Assembly immediately becomes suspended and then closes.

### ISSUE THREAD

**Issue by MuptezelSamet636** [XboxChaos/Assembly#231]
**Describe the bug**
Whenever I try to run Assembly it immediately becomes suspended and then closes on itself.

**To Reproduce**
Double-clicking Assembly.exe shows up on the task manager but immediately becomes suspended then a few seconds later closes on itself.

**Expected behavior**
Assembly never shows up on the taskbar or the pop-up message when you launch the program

**PC (please complete the following information):**
 - OS: Windows 10 Professional 64-bit

**Additional context**
I already downloaded all the software that was needed for Assembly and funny enough Initial release of Assembly works perfectly fine but later releases never open.

**Comment by Akarias** [comment]
Sounds like its looking for the assembly icon library dll and failing to do so.

**Comment by MuptezelSamet636** [comment]
Any recommendation?

**Comment by ThunderWaffle** [comment]
I'm aware of a bug with startup.  Can you check for the presence of Assembly.exe.config?

**Comment by MuptezelSamet636** [comment]
Yes Assembly.exe.config is present in the folder

**Comment by ThunderWaffle** [comment]
Can you try the version located here?  This one is built with the xdevkit dependency turned off.  I'm wondering if builds with that on after the changes made to make it optional aren't stable.

https://ci.appveyor.com/project/ThunderWaffle/assembly/builds/29534244/artifacts

**Comment by MuptezelSamet636** [comment]
This time Assembly.exe shows up on the task manager then immediately closes on itself.

**Comment by ThunderWaffle** [comment]
One more thing to try.  Backup version.json and delete it.  See if it the program launches.

**Comment by tleachman1234** [comment]
Having the same issue here. If I use the latest release from the stable downloads it works, however poking doesn't seem to be able to find the game in that version (only tested on forge world so far). I tried to update because I saw elsewhere that there was a fix allowing poke to edit the memory files, but I can't use assembly at all with this new bug it brings. Are there any updates on this issue?

**Comment by Lord-Zedd** [comment]
Which latest release do you mean?

**Comment by tleachman1234** [comment]
I pulled down the binary, I didn't compile from source. I meant I used the latest release of the downloader [here](https://github.com/XboxChaos/Assembly/releases) (sorry for the confusion on that). When downloading and choosing the dev branch, the program works as expected. However on first run it asks to install the latest update. Updating brings about the issue keeping the application from opening.

This said though, after seeing [your commit](https://github.com/XboxChaos/Assembly/commit/608529b3378331071c52a2c3e16ab463c63040e6) I figured out pretty quickly that I could fix the poking problem by manually editing the version number in the xml file. I didn't realize it was such a simple fix when I first posted, so this could be a workaround for those who can't update like I described

**Comment by ThunderWaffle** [comment]
@MuptezelSamet636 Can you grab the latest version using the downloader in the releases for this repo?  Curious if some of the stuff we did in the update we pushed today resolved this.

**Comment by MuptezelSamet636** [comment]
@ThunderWaffle Sorry for the late reply. I just tried the latest version using the downloader and it worked. Assembly opened even tried the map patcher and it worked great!

**Comment by 0xdeafcafe** [comment]
Are you happy to close the issue then?

**Comment by MuptezelSamet636** [comment]
Yep
