### ISSUE TITLE
Value cannot be null.Parameter name: tag is null

### ISSUE THREAD

**Issue by SoulMystique** [XboxChaos/Assembly#232]
I have literally no idea what this is, but it's bugging out all but one of my custom weapons, preventing it from being imported. 

System.ArgumentNullException: Value cannot be null.Parameter name: tag is null   at Blamite.Injection.TagContainerInjector.InjectTag(ExtractedTag tag, IStream stream)   at Blamite.Injection.TagContainerInjector.InjectResource(ExtractedResourceInfo resource, IStream stream)   at Blamite.Injection.TagContainerInjector.FixResourceReferences(DataBlock block, IWriter buffer, IStream stream)   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream, ITag tag)   at Blamite.Injection.TagContainerInjector.InjectDataBlock(DataBlock block, IStream stream)   at Blamite.Injection.TagContainerInjector.FixBlockReferences(DataBlock block, IWriter buffer, IStream stream)   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream, ITag tag)   at Blamite.Injection.TagContainerInjector.InjectTag(ExtractedTag tag, IStream stream)   at Blamite.Injection.TagContainerInjector.FixTagReferences(DataBlock block, IWriter buffer, IStream stream)   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream, ITag tag)   at Blamite.Injection.TagContainerInjector.InjectDataBlock(DataBlock block, IStream stream)   at Blamite.Injection.TagContainerInjector.FixBlockReferences(DataBlock block, IWriter buffer, IStream stream)   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream, ITag tag)   at Blamite.Injection.TagContainerInjector.InjectTag(ExtractedTag tag, IStream stream)   at Blamite.Injection.TagContainerInjector.FixTagReferences(DataBlock block, IWriter buffer, IStream stream)   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream, ITag tag)   at Blamite.Injection.TagContainerInjector.InjectDataBlock(DataBlock block, IStream stream)   at Blamite.Injection.TagContainerInjector.FixBlockReferences(DataBlock block, IWriter buffer, IStream stream)   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream, ITag tag)   at Blamite.Injection.TagContainerInjector.InjectTag(ExtractedTag tag, IStream stream)   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.btnImport_Click(Object sender, RoutedEventArgs e)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)   at System.Windows.Controls.Primitives.ButtonBase.OnClick()   at System.Windows.Controls.Button.OnClick()   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)   at System.Windows.Input.InputManager.ProcessStagingArea()   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean

**Comment by radiian** [comment]
I'm having a similar issue. Steps I've done to recreate the problem:

1. Export a default tag from one map
2. Import it to another map
3. Duplicate and rename the default tag
4. Export and then reimport to a fresh map
5. Null reference exception

I've had some luck by only checking "inject raw data" during tag injection, but all of the values get nulled out. I've had better luck if I import the default tag first, and then import the renamed duplicate but things still get broken in weird ways.

**Comment by Lord-Zedd** [comment]
is this still happening?
