### ISSUE TITLE
Cannot access game process due to Anti-Cheat.

### ISSUE THREAD

**Issue by LordSquishers** [XboxChaos/Assembly#233]
While trying to Poke into Reach MCC (forge_map), this error occurs. On the latest dev version.

`System.InvalidOperationException: Cannot access game process due to Anti-Cheat.   at Blamite.RTE.MCC.MCCRTEProvider.GetMetaStream(ICacheFile cacheFile)   at Assembly.Metro.Controls.PageTemplates.Games.Components.MetaEditor.UpdateMeta(SaveType type, Boolean onlyUpdateChanged, Boolean showActionDialog)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)   at Xceed.Wpf.Toolkit.DropDownButton.OnClick()   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)   at System.Windows.Controls.Primitives.ButtonBase.OnClick()   at System.Windows.Controls.Button.OnClick()   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)   at System.Windows.Input.InputManager.ProcessStagingArea()   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean`

**Comment by Ethos117** [comment]
What branch did you download?

**Comment by LordSquishers** [comment]
2019.12.10.18.40.00-dev from the release page

**Comment by Ethos117** [comment]
Here, Hop on in. https://discord.gg/y2uSBU

**Comment by ThunderWaffle** [comment]
Did you launch the game with anticheat turned off?  Assembly doesn't support poking the game with anticheat on.

**Comment by Lord-Zedd** [comment]
If you are for sure running without anticheat, try restarting your PC. I've been hearing other people mention this and it appears to be a bug with the game's anticheat protecting the game process even when you didn't want it to.

**Comment by Ethos117** [comment]
He got it. Had to launch as admin.
