### ISSUE TITLE
Corrupted map trying to import new elite biped tag

### ISSUE THREAD

**Issue by matty45** [XboxChaos/Assembly#235]
> System.NullReferenceException: Object reference not set to an instance of an object.   at Blamite.Injection.TagContainerInjector.InjectPrediction(ExtractedResourcePredictionD pred)   at Blamite.Injection.TagContainerInjector.InjectPredictions(ICollection`1 predictions)   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.btnImport_Click(Object sender, RoutedEventArgs e)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)   at System.Windows.Controls.Primitives.ButtonBase.OnClick()   at System.Windows.Controls.Button.OnClick()   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)   at System.Windows.Input.InputManager.ProcessStagingArea()   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean

How to replicate:
1. rename old elite biped tag.
2. import new elite biped tag.
3. bug

**Comment by Lord-Zedd** [comment]
is this still happening?

**Comment by matty45** [comment]
Nope, this issue can be safe to close now.
