### ISSUE TITLE
Weird issue with duplicating tags.

### ISSUE THREAD

**Issue by matty45** [XboxChaos/Assembly#236]
**Bug Description**
A strange bug seems to happen when trying to use duplicated tags in-game, causing the game to crash.

**How to reproduce**
1. [Follow through this tutorial to make a working ai spawner, just set anticipated tag to rahc for it to work.](https://www.xboxchaos.com/topic/4321-ai-spawns/)
2. Add the scen to the forge menu.
3. Duplicate the effe and scen to make another similar entry to the forge menu, only with a different char and string identifier
4. Try spawning the duplicated scen in-game.

**Expected behavior**
I expected the ai to spawn properly without any issues.

**Videos**
https://streamable.com/shwfv

**PC:**
 - OS: Windows 10 Pro

**Additional context**
Sometimes duplicating the tag works without issues, sometimes it does not.

**Comment by Lord-Zedd** [comment]
If it only happens sometimes, is there any exact tags this occurs on?

**Comment by matty45** [comment]
it only happens on the duplicated scen tag thats been put into the forge menu

**Comment by matty45** [comment]
never mind, this was all human error in the end. turns out i missed a few fields in a tag that i forgot to change.
