### ISSUE TITLE
Cant find CL.exe

### ISSUE THREAD

**Issue by Acronical** [XboxChaos/Assembly#237]
I've got a little bit of an error when trying to build Assembly. Its my first time downloading it. When I open the solution and try and build, I get this error:

Error	TRK0005	Failed to locate: "CL.exe". The system cannot find the file specified.	

I have no idea what this means because I am a big noob. Any ideas on how to fix this so that I can build. If you need to know anything, I'll answer what I can.

**Comment by adierking** [comment]
You need to have C++ support enabled in Visual Studio in order to build Assembly.

If all you want is a working program and you don't plan on editing the source code, you can grab a prebuilt version from Nexus Mods: https://www.nexusmods.com/halothemasterchiefcollection/mods/1
