### ISSUE TITLE
This isnt really a bug but a feature request

### ISSUE THREAD

**Issue by Arttumiro** [XboxChaos/Assembly#238]
When pressing the "search for a tag" button assembly always opens it on a default location, it would be really helpful if it remembered its last location, especially if you are using 2 screens, since assembly always opens the prompt on my main monitor even if assembly is open on my secondary.
No need to be fast with adding it in if you even decide to do so, just a small annoyance of mine

**Comment by 0xdeafcafe** [comment]
@Arttumiro Does that change fix your issue?

**Comment by Lord-Zedd** [comment]
closing with the assumption that its fine now

**Comment by Arttumiro** [comment]
Ahh yeah its all fine, apologies i havent been looking at github
