### ISSUE TITLE
Still can't find CL.exe

### ISSUE THREAD

**Issue by Acronical** [XboxChaos/Assembly#239]
I already made a post about Cl.exe not being found and got a response but it still can't be found so I thought I'd be more descriptive. I want to mod reach on the pc mcc so I download assembly here: https://github.com/XboxChaos/Assembly/tree/dev_mcc . Then I put the devkit in XBDMCommunicator. I open up the solution and and try to build assembly. This is where the problem happens. I get the error:

Error	TRK0005	Failed to locate: "CL.exe". The system cannot find the file specified.	

I uninstalled "Desktop development with C++" and reinstalled it thinking the file was just missing. However, I still got the same error. I checked my pc and cl.exe isn't anywhere on my pc. Is there a way for me to get it. I already uninstalled C++ and reinstalled it. Is it possible that my installer is bad. It is the visual studios installer and it is up to date. I used this video to follow and install: https://www.youtube.com/watch?v=ygzJvCNeLp8 . I assume that the problem is I literally don't have CL.exe but I don't know how I can get it. I can answer anything you want to know. Sorry for posting again, I've have just had no luck with anything. Also, I'm using windows 10.

**Comment by adierking** [comment]
I think the issue may be that you need the Visual Studio 2015 toolset installed. I don't remember how to configure that.

In any case, though, that video is out-of-date. You should download Assembly from Nexus Mods if you don't know how to use Visual Studio: https://www.nexusmods.com/halothemasterchiefcollection/mods/1

**Comment by Acronical** [comment]
I downloaded it from where you sent me and everything work. Thank you.
