### ISSUE TITLE
Engine not supported error

### ISSUE THREAD

**Issue by Acronical** [XboxChaos/Assembly#241]
I'm back with another problem due to my lack of knowledge. I open up assembly and when I try to open a .map file in it, I get the error:

Engine not supported. 
Why not add support in the 'Formats' folder?

All the other files open in assembly (.mapinfo, .blf, .campaign).  I also can't find the formats folder. Any ideas on how to fix this?

**Comment by ChasingAir** [comment]
Had this same issue on v2016.11.04.19.07.00-master. I downloaded the official "Downloader" from [here](https://github.com/XboxChaos/Assembly/releases/tag/downloader).
I used that to download the latest dev branch (v2019.12.10.18.40.00-dev) and now it works great.

**Comment by Acronical** [comment]
Thank you, this worked.
