### ISSUE TITLE
Reach PC - Scenario squads weapon tag editor changes both character and weapon for Squad A on indices greater than 0

### ISSUE THREAD

**Issue by BobDoleOwndU** [XboxChaos/Assembly#242]
If Squad A in the scnr's squad tag has more than one index, going to an index greater than 0 and changing the index of the squad's weapon will change both the character and the weapon to the set index.

**To Reproduce**
1. Load m20.map in Assembly.
2. Open m20.scnr.
3. Go to the Squads section.
4. Set the index to 62
5. Under Squad A set the index to 1 (for jackals).
6. Under weapons, change the weapon palette index to any value. (4 for example for the needler.)
7. Load ONI: Sword Base in game.
8. Poke changes in assembly and reload the mission in game.
9. The jackals that spawn in the middle of the courtyard will now have swapped to whatever character matches the index of the weapon, along with their weapons being swapped to the same index. (Using 4 as an example, they will be swapped to grunt heavies with needlers.)

**Comment by Lord-Zedd** [comment]
closing because the isolation feature solves this
