### ISSUE TITLE
netpoke2 - Client crashes when someone pokes

### ISSUE THREAD

**Issue by matty45** [XboxChaos/Assembly#252]
For some reason one of the clients on my network poking server has his assembly crash when someone pokes changes.

https://i.imgur.com/IElXJyp.png

**Comment by matty45** [comment]
Nevermind, he was being stupid and was had EAC enabled.

**Comment by matty45** [comment]
I think there should be a error for eac like it does with the normal build of assembly.

**Comment by ThunderWaffle** [comment]
This _should_ have been handled by the local RTE provider.  I can see if there's something I missed.

**Comment by ThunderWaffle** [comment]
I believe these exceptions are shown with the MetroException dialog now that I've straightened out the background workers.
