### ISSUE TITLE
Group Poking - Adding address to a block crashes the game

### ISSUE THREAD

**Issue by matty45** [XboxChaos/Assembly#254]
For some reason, adding a address to a unallocated block in the scnr tag crashes the game for all clients except the host.

Steps to reproduce 
1. Go to globals\game_results and copy an address from one of the blocks then null it.
2. Go to the maps scnr and weather block and paste in the address and set count to one.
3. Poke.

**Comment by ThunderWaffle** [comment]
Despite having group poke, some things just won't ever work.  I'd encourage you to try 2 separate game sessions.  Group poke still works if you're in the game in separate sessions.  See if this still crashes the group poke clients.  If it does not, you're looking at an engine limitation.

**Comment by executionByFork** [comment]
You should try setting the count first, poking, and then setting the address. I think assembly doesn't always do things in order, and so it tries to add the address before increment the count, causing the crash. I've had separate instances where my method of increasing the count, poking, and then adding the address works without crashing the game
