### ISSUE TITLE
I started a Wiki. Please add things

### ISSUE THREAD

**Issue by MegaMech** [XboxChaos/Assembly#256]
Hello,
If I have missed any intricate details about Assembly in the wiki Getting Started page that I created, please add information. Even if you only have time to list a couple things in point form at the bottom, I'll get the jist of it and can re-write it in an intelligible manner.

I think I am going to write about three guides that just cover a few modding basics that some people will want to do. Perhaps this is useless and we'll never have lots of modders?

I find the hardest part about modding halo is just the lack of documentation or the lack of easily accessible documentation. Things like How does Assembly work? What does it actually do? What issues are created when deleting tags that warrant that feature not being implemented.

The forums are okay, but it's not great because half of posts in the guides category are questions and important guides are not pinned to the top.

**Comment by adierking** [comment]
Hey, it looks like you put a lot of effort into those guides - that's awesome!

The wiki is intended to be for the people actually developing Assembly itself, though. Most people who are using Assembly to create mods will never look at it (or even this GitHub in general). It wouldn't be fair to you to let you keep working here, and we don't want more tutorials to be added here, so we went ahead and reverted the changes. (Don't worry, nothing is lost - just clone `https://github.com/XboxChaos/Assembly.wiki.git`.)

You're welcome to post your guides on xboxchaos.com or any other site where people will be more likely to see them. We know that there might not be a great solution for people looking for Reach MCC guides right now, but the GitHub wiki definitely isn't the right place. I've heard through the grapevine that there may be some people interested in setting up a wiki elsewhere - perhaps check the halomods Discord?

**Comment by MegaMech** [comment]
I doubt the Wiki will ever be used for that purpose though. I have seen other Github projects use the Wiki as a tool to thoroughly instruct users on how to use their software.

**Comment by MegaMech** [comment]
Hi Adierking,

My goal was actually to inspire you and the other developers to write about the technical details of Assembly. How does it save? Load? Import? Export? Does it over-write the whole file? Load the whole file into ram? Does stopping import half-way through corrupt the whole file or only the header and why? Rather than passing off the valuable resource provided to you, you could have suggested a topic and some facts that are within the scope of the Wiki for me to write about.

If you review xboxchaos/Nitrogen, you will see the Wiki has some instructional information about the programs use. Please be consistent and remove that information, or admit that some instruction is relevant to this wiki and define that scope. I do not see how the Wiki cannot achieve both goals: For Assembly developers and normal users. In my perspective, you are actively rejecting the ability for users of Assembly to easily access instructional materials. Do you not want to increase the size of the Halo modding community? Did you not consider leaving the Wiki as is on a temporary basis until an actual Wiki can be designed?
