### ISSUE TITLE
Index mixups corrupt tags

### ISSUE THREAD

**Issue by MegaMech** [XboxChaos/Assembly#258]
I think Assembly has a bug where it mixes up index's.

m70.map, bed_long.hlmt. Variants>index[1] (container_long)

Objects > Add 1 through tag block re-allocator.
Insert machine gun as the object and add marker. Run game.
Add three more index's through the "i" button.

Now the first index has what I inputted with machine gun. Index 2 shows as:
Address: 0x1CBEDE0F0
Parent Marker/Child Marker: hitch_connect
Object Variant: tanker_long
Object: vehi[bed_long]
That stuff isn't supposed to be there. It's supposed to be empty
I believe doing this corrupts the tag as whenever I place the vehicle truck_cab_large through the forge editor it crashes the game.

Addresses:
Variants: 0x1CC0F1E80 (3 index)
Objects: 0x1CBEDE0F0 (Variant index 2)

This could be related, but when I add markers to truck_cab_large it corrupts the tag constantly. When I go to place the vehicle in-game it crashes. (Game loads, select vehicle, crash)

OS: 8.1

**Comment by Lord-Zedd** [comment]
You should not be adding more block elements through the "i" button.
