### ISSUE TITLE
Assembly Flop

### ISSUE THREAD

**Issue by ConfusedApe** [XboxChaos/Assembly#264]
**Describe the bug**
Error when compiling:

Error occurred while restoring NuGet packages: Invalid restore input. UAP projects must contain exactly one target framework. Input files: C:\Users\jeff\Documents\Assembly-dev_mcc\src\Blamite\Blamite.csproj, C:\Users\jeff\Documents\Assembly-dev_mcc\src\Blamite\project.json.
1>------ Build started: Project: AssemblyIconLibrary, Configuration: Debug x64 ------
1>main.cpp
1>AssemblyIconLibrary.vcxproj -> C:\Users\jeff\Documents\Assembly-dev_mcc\src\AssemblyIconLibrary\\bin\AssemblyIconLibrary.dll
1>AssemblyIconLibrary.vcxproj -> C:\Users\jeff\Documents\Assembly-dev_mcc\src\AssemblyIconLibrary\\bin\AssemblyIconLibrary.pdb (Full PDB)
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**To Reproduce**
Open assembly.sln

**Expected behavior**
I expected Assembly to start.

**Screenshots**

**PC (please complete the following information):**
 - OS: Windows 10 Home; version 1909; OS build 18363.535

**Additional context**
I installed Windows Build Tools 2015,  Windows 8.1 SDK and xdevkit.dll. At first there was a .Net 4.5 problem, which Visual Studio took care of - downloaded stuff. The problem was that the . Net 4.5 target was not there, so I closed the dialogue box and then Visual Studio did its thing. After that Assembly showed up in the IDE. I was not prompted with anything, and pressed play.

**Comment by matty45** [comment]
Have you tried restoring the nuget packages manually?
