### ISSUE TITLE
Tentative d

### ISSUE THREAD

**Issue by n0rm4lg4m3r** [XboxChaos/Assembly#281]
i downloaded assembly and it ran but said "System.UnauthorizedAccessException: Tentative d'exécution d'une opération non autorisée.
   à Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   à Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   à Assembly.Helpers.AssemblyProtocol.UpdateProtocol()
   à Assembly.App.OnStartup(StartupEventArgs e)
   à System.Windows.Application.<.ctor>b__1_0(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)" and when i clicked continue, it closed

**Comment by 0xdeafcafe** [comment]
Can you try running it as Administrator?

**Comment by n0rm4lg4m3r** [comment]
i tried and it just doesn't lauch
