### ISSUE TITLE
Engine not supported

### ISSUE THREAD

**Issue by MeisterXehanort** [XboxChaos/Assembly#285]
System.NotSupportedException: Engine not supported   bei Blamite.Blam.CacheFileLoader.LoadCacheFile(IReader reader, EngineDatabase engineDb, EngineDescription

**Comment by MeisterXehanort** [comment]
wat i can do?

**Comment by Krakenlord69** [comment]
I think I have the same problem for opening maps since the MCC update of the 12th may: [image](https://i.postimg.cc/J4yJy95y/bug.png)

**Comment by MeisterXehanort** [comment]
By me is it not fixed :(

Krakenlord69 <notifications@github.com> schrieb am Fr., 15. Mai 2020, 17:15:
