### ISSUE TITLE
Engine version not supported

### ISSUE THREAD

**Issue by Silverpelt2475** [XboxChaos/Assembly#286]
When i try to open a .map file with assembly i get an error that says "Mar 24 2020 12:10:36 not supported. why not add support in the 'formats' folder" this happens with every .map file and i have the most up to date Assembly. Any suggestions?
![ERROR](https://user-images.githubusercontent.com/65420909/82089896-61792900-96ec-11ea-8789-2e3b55270d72.PNG)

**Comment by KaseRadtke** [comment]
You need to update the Poking XML's in the formats folder. See https://github.com/XboxChaos/Assembly/commit/608529b3378331071c52a2c3e16ab463c63040e6#diff-d578bfa01cf9e1e74bb2ca892ed08e2e for the latest build version.

**Comment by KaseRadtke** [comment]
You need to update the engines.xml file with the newest versions. Check https://github.com/XboxChaos/Assembly/blob/dev/src/Blamite/Formats/Engines.xml for the latest.

**Comment by Silverpelt2475** [comment]
Thank you

**Comment by Auspiciius** [comment]
I had the same issue, however when I attempted to update the Engines.xml file in the Formats folder I encounter problems. At first, I tried copying the code from the link in order to create a new file which I named Engines.xml. However, this seems to bug out Assembly upon launching it s the program would not launch at all. What is the correct way to update this file in order to fix the issue of the outdated Engines.xml file?

**Comment by KaseRadtke** [comment]
> I had the same issue, however when I attempted to update the Engines.xml file in the Formats folder I encounter problems. At first, I tried copying the code from the link in order to create a new file which I named Engines.xml. However, this seems to bug out Assembly upon launching it s the program would not launch at all. What is the correct way to update this file in order to fix the issue of the outdated Engines.xml file?

Honestly, the simplest way would be to just clone/re-download the most recent build from here and compile it again so everything is completely fresh and updated.

**Comment by Auspiciius** [comment]
I actually just copied the entire formats folder from the most recent build and put it in with the rest of the files. It worked. So essentially you are right. Thanks for the advice.

**Comment by Caboose19** [comment]
I have this issue as well I have tried to copy the updated xml and that didn't fix it i just downloaded Assembly and it says there are no new updates, does anyone have any ideas on how to fix it.

**Comment by WildTom1** [comment]
When I put in the code Assembly won't launch at all.
