### ISSUE TITLE
Engine not supported Jun 5 2020

### ISSUE THREAD

**Issue by Anon-Linear** [XboxChaos/Assembly#297]
I am currently using the most recent version of Assembly, 2020.03.06.20.30.00-master. Whenever I try and open any of the map types I get an error similar to the previous 'Engine not supported' support pages. I have seen that there I need to update my engines.xml but whenever I try and update the code assembly will no longer run and I will need to download a fresh copy. 

I am not sure if the updated .xml code, found here: 
> 
> 
> You need to update the engines.xml file in the Formats folder with the newest versions. Check https://github.com/XboxChaos/Assembly/blob/dev/src/Blamite/Formats/Engines.xml for the latest.

Is up do date or not. I don't know if I am doing something wrong or just need to be more patient for a newer patch.

**Comment by Anon-Linear** [comment]
![image](https://user-images.githubusercontent.com/64250052/89738975-e1443480-da4a-11ea-91cd-eef01c2ef301.png)
here is an image of the error

**Comment by Lord-Zedd** [comment]
Switch to the experimental update branch. Master is a bit behind as we arent quite sure what to do with it.

**Comment by Anon-Linear** [comment]
thanks that worked

**Comment by Crinon** [comment]
Hello, I still have this problem even with the dev version
[
![image](https://user-images.githubusercontent.com/48944000/93665210-ff06af80-fa74-11ea-95c6-746f105d3056.png)
](url)

This is not the expermimental part ?
