### ISSUE TITLE
Colorf Discrepancy

### ISSUE THREAD

**Issue by theHostileNegotiator** [XboxChaos/Assembly#298]
Colorf present values that are not representative of the actual float values.
For example in H2, needler projectile, using colorf, the Hex code of the Color Lower Bound is CA47EA. Using float values (Using point3 for easy reading), multiplying by 255 and converting to hex results in 9710D1.
![image](https://user-images.githubusercontent.com/61142710/90100706-9abf4480-dd80-11ea-97c2-3fd47413fa47.png)
![image](https://user-images.githubusercontent.com/61142710/90105137-c0e8e280-dd88-11ea-8df1-2809182559b9.png)

This is reinforced by the values in H2Guerilla
![image](https://user-images.githubusercontent.com/61142710/90100876-ee319280-dd80-11ea-9df0-d1bd6f87d39d.png)
![image](https://user-images.githubusercontent.com/61142710/90105004-897a3600-dd88-11ea-88f0-ba3abfdb411d.png)

**Comment by Lord-Zedd** [comment]
So this is a tricky one. Assembly *used* to multiply by 255, but I found in later games this did not appear to be the case, with them instead opting for scRGB. https://twitter.com/zeddikins/status/1186426511148097536
While its certainly possible that H2 doesn't do that, I'll see how things look ingame.

**Comment by theHostileNegotiator** [comment]
OK
I noticed with the Needler projectile throughout all games have the same color in that function block, but that could be leftover. When looking at the Elite Bipd tag in Halo 3, the color seems to be accurate to the in game result as just multiplying by 255 made it seem very dark.
Then looking back at the Elite tag in Halo 2, the Major's armor would suggest that it is orange when it is red in game. So as you said, the scRGB it's something for the later games, H3 and onwards, while Halo 2 and 1 just multiplies the float values by 255.

**Comment by theHostileNegotiator** [comment]
Although comming back to this point, it is possible that some things don't use scRGB. Looking at the Reach subtitles, it just multiplies by 255
The image below with Assembly Hex on the left and the float x255 on the right, you can barely see that the scRGB is not representative of the subtitle color
![image](https://user-images.githubusercontent.com/61142710/90308526-84052300-df23-11ea-8d2d-056c0988cb1a.png)
![image](https://user-images.githubusercontent.com/61142710/90308555-c29add80-df23-11ea-94cf-01bcc7e71caf.png)
