### ISSUE TITLE
Add support for spheres/pills

### ISSUE THREAD

**Issue by Gr33nKn1ght** [XboxChaos/Assembly#320]
Currently I think only polyhedrons can be used for collision. Bipeds cannot use polyhedrons and use pills and spheres. If there could be an option to use ONLY spheres and pills and add support for them, then we could use this tool for bipeds.

**Comment by Lord-Zedd** [comment]
Anything like that would be an engine limitation. If the tag doesn't have it then the engine doesn't support them.
