### ISSUE TITLE
Assembly won't launch

### ISSUE THREAD

**Issue by Surasia** [XboxChaos/Assembly#322]
**Describe the bug**
Whenever I click the .exe, it does absolutely nothing. I have compiled the source and it says Object reference not set to an instance of an object.' and goes into sleep mode.

**To Reproduce**
1. Go to your assembly folder
2. Click on Assembly.exe
3. See error

**Expected behavior**
It was supposed to launch

**PC (please complete the following information):**
 - OS: [Windows 10

**Additional context**

Im using a ryzen 5 1600 and rx 5600 xt. I also tried compiling 4 times but it would say Object reference not set to an instance of an object.'

I found an old version which somehow worked but It was 5 years old.

**Comment by canbey1** [comment]
yeah me too old version worked well but new version not open to me same error

**Comment by canbeyy1** [comment]
can  you fixed my assembly not working too not open please help me
