### ISSUE TITLE
= Halo 3 =  Engine Version Not Supported Error

### ISSUE THREAD

**Issue by DukeZilla** [XboxChaos/Assembly#327]
Any map I try to open from Halo 3 I get this error:
```
Engine Version "Nov 24 2020 15:47:48" not supported.
Why not add support in the 'Formats' folder?
```

**Comment by 0xdeafcafe** [comment]
Go into settings and set the channel to experimental, and then check for updates again.

**Comment by fassetar** [comment]
Nice this helped me @0xdeafcafe
