### ISSUE TITLE
Patch Poking

### ISSUE THREAD

**Issue by kodifiretvsticks** [XboxChaos/Assembly#335]
It seems like Patch Poke menu or button does not work?
It returns a error "System.NullReferenceException: Object reference not set to an instance of an object".

Can this be fixed or is it turned off on purpose?

**Comment by Lord-Zedd** [comment]
I pushed a fix but it might not end up available via the downloader for the time being, for now the fix is available through appveyor https://ci.appveyor.com/project/ThunderWaffle/assembly/build/artifacts

**Comment by kodifiretvsticks** [comment]
thank you so much! I'll compile a copy and try it out now.

**Comment by kodifiretvsticks** [comment]
fantastic! works just as expected :)
