### ISSUE TITLE
Halo 2 - Engine not supported

### ISSUE THREAD

**Issue by TheSacredBird** [XboxChaos/Assembly#336]
Getting this error with any halo 2 .map files.

System.NotSupportedException: Engine not supported   at Blamite.Blam.CacheFileLoader.LoadCacheFile(IReader reader, EngineDatabase engineDb, EngineDescription

**Comment by djc5166** [comment]
Same error here.

On 2021.06.25.16.20.00-dev

**Comment by A267-dev** [comment]
Have you Decompressed Your Map Files? and Double Checked your Version of Halo 2 to see if it's Supported?
