### ISSUE TITLE
Update for latest MCC version?

### ISSUE THREAD

**Issue by Underinflated** [XboxChaos/Assembly#341]
The version of Assembly I have says it supports MCC's season 6.

Obviously it's season 7 now, and I was wondering if there's an update to make Assembly work again.

I tried modifying the various "poking" files, but I don't know the new headerPointer, headerAddress or magicAddress information, so that didn't work.

I don't know if Assembly is still being worked on, or if the project is abandoned, but thanks to anyone who can help! :)

**Comment by Lord-Zedd** [comment]
Assembly is still being updated for every MCC update, the changes have been going in the Experimental update channel (Dev if using the downloader app). This can be switched in Settings>Update Channel.

**Comment by Underinflated** [comment]
Okay.
This was probably something I should've been able to figure out on my own so,
thank you!
