### ISSUE TITLE
Resizing Tag Block in Halo 4 campaign can break gameplay

### ISSUE THREAD

**Issue by JoshTheGameDev** [XboxChaos/Assembly#343]
Adding a Target Tracking type on the Rocket Launcher and any other weapon in mission m40 (Reclaimer) will break the Target Locator and cause the mission to be unplayable. 

Issue extends to adding to a Tag Block of any type. 

Possibly affecting the script or trigger used for it.

**Comment by A267-dev** [comment]
It doesn't do that for me, How big of a block are you resizing? and what Version of Halo 4 are you editing?

**Comment by JoshTheGameDev** [comment]
The latest PC MCC version - Steam. (Build ID 7043710) 
I've managed to repeat this using a backup of the map I made before editing too.

From a clean m40_invasion.map file, all I do is: 
- Go to storm_rocket_launcher.weap
- Target Tracking
- Under "Tracking Types" add 1 new element
- Call it "ground_vehicles" 
- Save
- Play from start of m40 (Reclaimer)
- Go up to the part where you have to obtain the Target Locater
- Try using the Target Locator on the Phantom objective 

It will just not allow you to use the item 

It has the same problem when trying to add a single element under Tracking Types for any other weapon too.

**Comment by 0xdeafcafe** [comment]
Hazarding a guess that this isn't an Assembly issue, but rather an issue with the engine itself.

**Comment by A267-dev** [comment]
@0xdeafcafe Gonna have to agree with you on this.

**Comment by Lord-Zedd** [comment]
Apologies for neglecting issues but this is due to the tracking types block being shared across multiple weapons. When adding elements old data is 0'd out to free it for use elsewhere which will break any other instances. Its probably way to late now but the solution would be to select "isolate shared block" underneath "add or remove elements" in the block gear menu.
