### ISSUE TITLE
ODST script bugs

### ISSUE THREAD

**Issue by six7six** [XboxChaos/Assembly#354]
When reading .map files from ODST; the scripting no longer compiles correctly. Functions like (game_difficulty_get_real) in the print_difficulty script have been replaced with (game_insertion_point_get), I'm not sure if the script component of assembly has been fully fixed but scripts no longer compile when trying to edit them after rendering out of guerilla/sapien. My bug is currently occuring on sc110 but I haven't tested on other maps yet.

![bug](https://user-images.githubusercontent.com/5703482/188294839-38b5c63c-b089-43f3-945a-75f7b88799df.JPG)

**Comment by Lord-Zedd** [comment]
Updated scripts weren't accounted for in the initial update. Updated xmls have been committed and can be grabbed from the repo/AppVeyor but I'm holding out for the Reach tools to push an update through Assembly itself.
