### ISSUE TITLE
Cannot build in Visual Studio CE 2022.  Missing `AssemblyIconLibrary.dll`

### ISSUE THREAD

**Issue by vegerot** [XboxChaos/Assembly#357]
**Describe the bug**
Trying to build in Visual Studio CE 2022 gives the following error

```markdown
Build started...
1>------ Build started: Project: Blamite, Configuration: Debug x64 ------
1>  Blamite -> C:\Users\Max\workspace\github.com\XboxChaos\Assembly\src\Blamite\bin\x64\Debug\Blamite.dll
2>------ Build started: Project: Assembly, Configuration: Debug x64 ------
2>  Feeds used:
2>    C:\Users\Max\.nuget\packages\
2>    https://api.nuget.org/v3/index.json
2>    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
2>  
2>  All packages listed in C:\Users\Max\workspace\github.com\XboxChaos\Assembly\src\Assembly\packages.config are already installed.
2>C:\Users\Max\workspace\github.com\XboxChaos\Assembly\src\Assembly\Metro\Controls\PageTemplates\Games\Components\Editors\ScriptEditor.xaml.cs(287,41,287,42): warning CS0168: The variable '_' is declared but never used
2>CSC : error CS1566: Error reading resource 'Assembly.AssemblyIconLibrary.dll' -- 'Could not find a part of the path 'C:\Users\Max\workspace\github.com\XboxChaos\Assembly\src\AssemblyIconLibrary\bin\AssemblyIconLibrary.dll'.'
========== Build: 1 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
========== Build started at 9:44 PM and took 01.653 seconds ==========
```

**To Reproduce**
1. Open Visual Studio
2. Open Assembly.sln
3. Select Build > Build Solution

**Expected behavior**
Assembly should build successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/5297725/221340991-54f2db31-1ba0-4708-ba8f-1eb9fd0a55b6.png)

**PC (please complete the following information):**
 - Windows 10
**Additional context**

**Comment by Lord-Zedd** [comment]
AssemblyIconLibrary is another project in the solution. Its currently configured for the 2019 toolset so its likely not building for you under 2022. Updating that should solve it.

**Comment by vegerot** [comment]
@Lord-Zedd honestly I had never used Visual Studio before.  What did the trick for me was the good 'ol turn if off and on again.  More specifically, I restarted Visual Studio and it built immediately!
