### ISSUE TITLE
[Suggestion] - Halo 5 Forge Support

### ISSUE THREAD

**Issue by NicmeisteR** [XboxChaos/Assembly#358]
I'm not sure about the technicality or if it's even possible but I'd love to see poking and just general support added for Halo 5 Forge.

**Comment by Lord-Zedd** [comment]
Its not something I want to pursue right now. I think the tool Reclaimer can open H5 and Infinite though.

**Comment by NicmeisteR** [comment]
No problem at all, will give Reclaimer a go!
