### ISSUE TITLE
assembly error catching service error

### ISSUE THREAD

**Issue by canbeyy1** [XboxChaos/Assembly#361]
I get this error when I click on the application can you help me solve this error please

![Ekran görüntüsü 2023-07-22 062647](https://github.com/XboxChaos/Assembly/assets/107968433/1b282d8e-5d25-4cdf-b1d0-a689b5babf35)

**Comment by Lord-Zedd** [comment]
So this is due to differences between the Turkish and English alphabet. Should be a straightforward fix.

**Comment by canbeyy1** [comment]
thanks ı fixed it change  language to windows and working now thank you lord zedd
