### ISSUE TITLE
Code Contracts

### ISSUE THREAD

**Issue by kornman00** [XboxChaos/Assembly#62]
I've noticed in a least one portion of your codebase you use Debug.Assert. Have any of you ever looked into MS Research's [CodeContracts](http://research.microsoft.com/en-us/projects/contracts/)? I've been using it since 2010 (you can checkout a brief example of how I use it in this [article's code](http://www.codeproject.com/script/Articles/ViewDownloads.aspx?aid=256984)) and haven't looked back. It's a lot more configurable and expressive than using System.Diag's Debug class or plan-old if-else-throw blocks that you normally precede your method's code with. You can also setup a build config to have it statically analyze your code using the contracts specified in your code.

In VS2012 they appear to list it in the Extensions downloads (albeit, it doesn't download in VS2012 itself).

If I was still actively developing BlamLib, I would have replaced a lot of re-developed wheels with Code Contracts.

If you do decide to roll with it, might I suggest adding a Requirements section to the Readme or wiki? E.g., I didn't realize I needed to have XDevKit.dll or w/e handy when I went to go build.

**Comment by 0xdeafcafe** [comment]
This issue didn't age well 😉 . Going too close as I think CC's are pretty much dead now?

**Comment by kornman00** [comment]
Yes. Yes, they are pretty much dead ;_;

I've been scrubbing them from KSoft this past week.

**Comment by 0xdeafcafe** [comment]
f
